### ISSUE TITLE
step组件缺少第三态

### ISSUE THREAD

**Issue by FE-Girl** [uxcore/uxcore-steps#1]
目前只有已完成和未开始，正在进行中的状态没有，希望可以加上第三态，如下图所示：
![image](https://cloud.githubusercontent.com/assets/6926706/10634448/68dd2304-7824-11e5-995f-9cc885dcd32c.png)

**Comment by peng2e** [comment]
同意楼上。 完成的是绿色实线， 进行中绿色虚线，未进行的灰色实线
