### ISSUE TITLE
希望增加点击数字的自定义事件，或者自定义渲染数字区域？

### ISSUE THREAD

**Issue by digitaloceanwork** [uxcore/uxcore-steps#11]
现在的Steps的onChange事件点击无效、icon自定义传参的时候把参数当成样式附加在最后一个元素上

**Comment by ex90rts** [comment]
1. onChange 的回调事件需要自己传入，回调会返回当前点击 Step 的 key 值，自己根据 key 值来处理
2. by design: icon 自定义本身就是需要自己写实现的，配置项只是提供一个 class 名称
