### ISSUE TITLE
 样式错乱

### ISSUE THREAD

**Issue by FE-Girl** [uxcore/uxcore-steps#5]
当只有一个step节点设置description属性时，样式错乱
![image](https://cloud.githubusercontent.com/assets/6926706/19225698/6a585ca0-8ed3-11e6-8578-c67dc0afbadc.png)
代码如下：
![image](https://cloud.githubusercontent.com/assets/6926706/19225750/1a27f000-8ed4-11e6-9c67-7fec4793eb21.png)

**Comment by macisi** [comment]
fixed
